FROM python:3.9-slim

WORKDIR /app

RUN pip install --upgrade pip setuptools wheel
RUN apt-get update -y && \
    apt-get install -y libhdf5-dev pkg-config gcc

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY model/dog_breed_classifier.py /app/

CMD ["python", "dog_breed_classifier.py"]
